### ISSUE TITLE
Add support for m3u IPTV lists

### ISSUE THREAD

**Issue by dikonov** [llelectronics/videoPlayer#25] opened 2018-05-16 11:00 UTC
I am using LLs player to watch IPTV, because it is the only app that can play almost any video stream from the web. Unfortunately, it is very inconvenient because of severely limited playlist support. All IPTV playlists are provided as M3U, but LLs player does not recognise it. I have to convert it to pls first.

Here is a list of the desired changes:
- support direct loading of M3U;
- support basic metadata (Channel names, logos, groups) and show channel names instead of truncated URLs, which look identical for different channels;
- autoloading of a default playlist or remembering of playlist paths for quick selection.

An example playlist entry looks like this:
```
...
#EXTINF: group-title="Swedish",Expressen TV
https://httpcache0-03837-cachelive2.dna.qbrick.com/03837-cachelive2/smil:03837_tx2_720p/playlist.m3u8
...
```

**Comment by llelectronics** [comment] 2018-05-16 11:07
Seems to be a duplicate of #23

**Closed by llelectronics** 2018-05-16 11:07 UTC
Labels: duplicate
